### ISSUE TITLE
npm 3 support

### ISSUE THREAD

**Issue by hswolff** [facebookarchive/react-page-middleware#28]
Just a kind FYI that this module is not compatible with npm v3. Due to how npm 3 changed where they place `node_modules` [this dynamic lookup of a node_modules](https://github.com/facebookarchive/react-page-middleware/blob/master/src/DefaultRouter.js#L146) fails as the `browser-builtins` package is no longer placed relative to this module. 

I came across this issue when trying to [run the `react-native` website locally](https://github.com/facebook/react-native/blob/master/website/package.json#L3).

**Comment by zpao** [comment]
That line should probably just be `require('browser-builtins').process`. Want to make that change and see if it solves the problem? We're not going to add features here but we should make sure our own websites continue to build :)

**Comment by zpao** [comment]
Well, I tried to close the wrong issue in the commit message but 4f4db543db07cb40490e7f003c7de2190e5ab7d0 fixed this (with what I suggested above).

**Comment by hswolff** [comment]
Woohoo, awesome! ty!

**Comment by jordwalke** [comment]
Thanks @zpao !

**Comment by hswolff** [comment]
I guess last thing needed here is to bump version number and bump dependency in react-native project?

**Comment by zpao** [comment]
Nah, this is the wild west, all of our projects using react-page-middleware [just point at the git url](https://github.com/facebook/react-native/blob/master/website/package.json#L16) 😀. I actually don't think we ever published this to npm. Just `rm -rf node_modules/react-page-middleware && npm install` (`npm update` might do a `git pull`, not sure)

**Comment by zpao** [comment]
But you will need to wait for https://github.com/facebook/react-native/pull/3786 since there was 1 other issue with npm 3.

**Comment by hswolff** [comment]
You're a modern day hero sir.
